### ISSUE TITLE
Crash when using weapon in autoclicker from Click Machine mod

### ISSUE THREAD

**Issue by Tander** [Shadows-of-Fire/ClickMachine#10]
Happens with these versions of the mods:
ClickMachine-1.14.4-2.1.2.jar
weapon_craftery-1.14.4-1.0-Beta-4.jar

How to reproduce: put any sword in Click machine and let it hit any mob (for example, vanilla chicken).

More info in crashlog:
[crash-2019-12-09_15.25.37-server.txt](https://github.com/stal111/Weapon-Craftery/files/3939600/crash-2019-12-09_15.25.37-server.txt)

**Comment by Shadows-of-Fire** [comment]
This would be a bug in the weapon craftery mod.
