### ISSUE TITLE
Server config

### ISSUE THREAD

**Issue by Flammable4444** [Shadows-of-Fire/ClickMachine#11]
It turned out, that it will show proper settings only if config edited on server AND on client side. I was modifying server config, but when i was using it, it seemed like it had default settings, but it only seemed that way, ticks and rf usage was changed, but it was just incorrectly shown. Not a big issue, but i had to scratch my head realy hard to figure out, that i also need to edit CLIENT config.

**Comment by Shadows-of-Fire** [comment]
Working as intended
