### ISSUE TITLE
[1.14.4] Auto Clicker crashes the Server/Game(?).

### ISSUE THREAD

**Issue by Gbergz** [Shadows-of-Fire/ClickMachine#12]
Forge-Version: **28.1.107**
MC-Version: **1.14.4**
Mod-Version: **2.1.2**

**Crash-Report:** [https://gist.github.com/Gbergz/c66171904c3a9cd12eedefd5d0128811](https://gist.github.com/Gbergz/c66171904c3a9cd12eedefd5d0128811)

Any ideas?
~ Gbergz

**Comment by Shadows-of-Fire** [comment]
it would appear this is a bug in simpleharvest
