### ISSUE TITLE
[1.15.2] Client hard crash when opening auto clicker

### ISSUE THREAD

**Issue by Quu1337** [Shadows-of-Fire/ClickMachine#15]
Was going to write long bugreport about stuff i tried, but it just crashes.
Opening the machine, if it has item in it or not, connected to power or not, it just always causes game to hard crash to desktop.

crash log: https://pastebin.com/vk043j94

forge: 31.1.0
click machine: 3.0.0

**Comment by tobi-polar** [comment]
I'm having the same issue. 

Crash log:https://pastebin.com/ZXPRubxY
Forge:forge-31.1.0
Minecraft:1.15.2
Modpack: All the Mods 5 v1.2

**Comment by Shadows-of-Fire** [comment]
click machine 3.0.0 is not for 15.2

**Comment by Quu1337** [comment]
if its not for 1.15.2, you should change curseforge tags to say something else than 1.15.2

**Comment by Shadows-of-Fire** [comment]
That file is not marked for 1.15.2.  Use the file marked for that version.
