### ISSUE TITLE
ClickMachine + Portal = Crash

### ISSUE THREAD

**Issue by Yamza** [Shadows-of-Fire/ClickMachine#16]
Using the autoclicker on any portal type block causes the server to crash. Example items would be the yamda mining dim portal or good night sleep's beds.

**Comment by Shadows-of-Fire** [comment]
Gonna need a crash report and a debug.log to do anything with this

**Comment by Yamza** [comment]
Crash report: https://hatebin.com/wuwzrtsoqp
Debug: https://gist.github.com/Yamza/a9ed8bbd48fe74ca79058a30ed2073bb
Latest: https://gist.github.com/Yamza/9ca38076000d9865f2025cda59275d77
