### ISSUE TITLE
Block refuses to resume regular activation after server reboots

### ISSUE THREAD

**Issue by dpcollier128** [Shadows-of-Fire/ClickMachine#19]
I've been playing with this mod on MC 1.15.2 with a server world, and the block operates properly during the same server session it gets placed.

However, once the server shuts down and resumes, the Auto Clicker block won't perform any clicks until it is broken and replaced.

I have currently tested this behavior with cocoa beans and sweet berries being the targets of each right-click action on setting 0 both with and without RF power. Strangely, the clicker will also operate without any power. But with or without power, the same refusal to reactivate occurs upon server reboot.

**Comment by Sim-ian** [comment]
I am having the same issue, using it on a Mystical Agriculture Farm with the Supremium Watering Can. The Clicker has power and works great, but always refuses to work when the server restarts until you break it and replace it. This is with the All The Mods 5 Pack latest version (1.16a).

**Comment by Shadows-of-Fire** [comment]
Is this still happening?  I just ran a machine through 3 server restarts with no issues, but that was in a development environment.

**Comment by DragarX** [comment]
I just posted a similar issue, where after a restart my machine will break, but instead of not working at all, it crashes my game upon interacting with an entity.
Not sure if they are related or not but thought I'd add my 2 cents.

**Comment by Shadows-of-Fire** [comment]
closing for lack of reproduction
