### ISSUE TITLE
Auto Clicker Crashed Server

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Shadows-of-Fire/ClickMachine#21]
A player on our server put a Magma Cube spawn egg in a spawner using the Auto Clicker as a killing machine for a mob grinder, and it crashed the server. The auto clicker seems to work fine with other mobs. The only way to bring the server back online was to restore a backup.

- Minecraft Version: 1.15.2
- Operating System: Linux (amd64) version 4.15.0-99-generic
- Java Version: 1.8.0_251, Oracle Corporation
- Forge: 31.2.20
- ClickMachine-1.15.2-3.0.2

[crash-2020-06-19_06.03.45-server.txt](https://github.com/Shadows-of-Fire/ClickMachine/files/4802421/crash-2020-06-19_06.03.45-server.txt)

**Comment by Shadows-of-Fire** [comment]
Appears to be an ftbquests bug
