### ISSUE TITLE
Server crash: Ticking block entity

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Shadows-of-Fire/ClickMachine#23]
A player set up a click machine to auto bone meal some potatoes and the server crashed in my modpack [Survival in Chaos](https://www.curseforge.com/minecraft/modpacks/survival-in-chaos/files/3052063)

Minecraft: 1.15.2
Forge: 31.2.36
ClickMachine: 1.15.2-3.0.2

https://pastebin.com/wDW8ZRsz

**Comment by Shadows-of-Fire** [comment]
This would be a bug in the simple farming mod, this isn't caused nor fixable by CM as far as I can tell.
