### ISSUE TITLE
Crash using weapon after server restart.

### ISSUE THREAD

**Issue by DragarX** [Shadows-of-Fire/ClickMachine#25]
I'm experiencing an issue where i have my clicker setup as a mob killer which works perfectly fine, but after a server restart if i turn my spawner back on it will crash instantly. the only way to cure this is revert to a backup and then break and replace the clicker. I'm on 1.15.2, but should be evident in the provided files.
Crash report and server log included. 
[2020-09-29-9.log](https://github.com/Shadows-of-Fire/ClickMachine/files/5302470/2020-09-29-9.log)
[crash-2020-09-29_15.29.22-server.txt](https://github.com/Shadows-of-Fire/ClickMachine/files/5302471/crash-2020-09-29_15.29.22-server.txt)

**Comment by Shadows-of-Fire** [comment]
That crash is from ftb quests, not click machine

**Comment by DragarX** [comment]
Ok since the crash is from FTB quests but is caused by the auto clicker killing a mob, I will need to speak to the ftb quests developer about fixing this issue?

**Comment by Shadows-of-Fire** [comment]
Yes, its probably related to fake player handling
