### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Rithenar** [Shadows-of-Fire/ClickMachine#26]
Have a click machine with a sword doing left clicks. I removed the sword but didn't disable or break down the clicker. After a few seconds server crashed and I got this crash log. https://gist.github.com/Rithenar/6188e713527d462000ad787a849afa21

**Comment by Shadows-of-Fire** [comment]
This was fixed in ac32797b06ec38bb01d11d6bd5a9ea316745b397
