### ISSUE TITLE
Crash on local server start up

### ISSUE THREAD

**Issue by Taccio33** [Shadows-of-Fire/ClickMachine#27]
1.16.4, forge 35.0.18
[crash-2020-11-19_16.39.12-server.txt](https://github.com/Shadows-of-Fire/ClickMachine/files/5567922/crash-2020-11-19_16.39.12-server.txt)
[crash-2020-11-18_14.40.57-server.txt](https://github.com/Shadows-of-Fire/ClickMachine/files/5567924/crash-2020-11-18_14.40.57-server.txt)

Could you add redstone control? The clicker seems to crash on load due to an overload apparently. removing and then adding the mod again seems to fix the problem, but at the nex star-up it appens again, suggesting that is the initial start up the problem. If a fix is not possible a redstone control could just work around the problem, limiting the use of the machine to specific cases.

**Comment by Shadows-of-Fire** [comment]
That crash is coming from Overloaded, you should report this to them.  It looks like they register an event handler for a common event intended to only receive clientside, but don't actually check that they're receiving it clientside or not and just blindly attempt to access the client player (which may not yet be loaded).
