### ISSUE TITLE
Swords in Click Machine disappear after a few minutes

### ISSUE THREAD

**Issue by papaworld** [Shadows-of-Fire/ClickMachine#29]
MC: 1.16.4
FML: 35.1.37
Click: 4.3.0 (and previous versions too)

Hi,

Swords inserted disappear after about 10 minutes of use. Durability is still high - Meka Refined Obsidian Sword 2450/2500. This also happens using vanilla swords with and without enchants.

Thank you.

**Comment by Shadows-of-Fire** [comment]
That's a tad bizarre.  I'll look into it

**Comment by papaworld** [comment]
Hi again, made a 1.16.5 instance with FML 36.0.1 and Click 1.16.4 4.3.0... same thing happens.

**Comment by Shadows-of-Fire** [comment]
cannot reproduce this, even after over an hour
