### ISSUE TITLE
Ticking block entity crash when using with Ex Compressum Sieve

### ISSUE THREAD

**Issue by Blackcatz1911** [Shadows-of-Fire/ClickMachine#31]
https://www.curseforge.com/minecraft/mc-mods/ex-compressum

Feeding the Sieve some Rotten Flesh will crash the game.

https://pastebin.com/uSi4dqyP

**Comment by Shadows-of-Fire** [comment]
crash report file is gone

**Comment by benbenlaw** [comment]
[crash-2021-06-03_20.35.54-client.txt](https://github.com/Shadows-of-Fire/ClickMachine/files/6593007/crash-2021-06-03_20.35.54-client.txt)

**Comment by Shadows-of-Fire** [comment]
This is... totally unrelated to clickmachine.
