### ISSUE TITLE
[1.16.5] FE/RF usage doesn't seem to function

### ISSUE THREAD

**Issue by ProspectPyxis** [Shadows-of-Fire/ClickMachine#33]
I've enabled the "Uses RF" config option, and the block does seem to say it can store 50,000 power, but so far, my attempts to power the device has failed with any means I have. I've tried the creative battery from Integrated Dynamics with auto-supply enabled, and some wires and generators from Silent's Mechanisms.

**Comment by Shadows-of-Fire** [comment]
Can't reproduce, I just hooked one up to a thermal combustion dynamo and it received and used power as intended.

**Comment by ProspectPyxis** [comment]
Weird...perhaps it's just an issue with the set of mods I'm using in particular, then. Ah well.
