### ISSUE TITLE
Item duplication

### ISSUE THREAD

**Issue by KyBeeS** [Shadows-of-Fire/ClickMachine#34]
Using the pickup function on a clicker with a wrench causes items internally to drop and be duped. Fix needed for atm6 hopefully so we don't have to fix it ourselves.

**Comment by Shadows-of-Fire** [comment]
The what now

**Comment by KyBeeS** [comment]
If you use any wrench with an ability to shift right click to pickup a machine on the clicker it dupes the inventory of the machine

**Comment by Shadows-of-Fire** [comment]
I would need a specific mod to be able to determine what it's doing that causes the double-drop

**Comment by KyBeeS** [comment]
Thermal, mekanism, as examples. Any wrench capable of picking up a machine with shift right click

**Comment by Shadows-of-Fire** [comment]
Closing as unsupported, authors of the wrench-adding mods have stipulated this is not their behavior, and it's not mine, so...
