### ISSUE TITLE
Shift Clicking into Click machine hard crashes 

### ISSUE THREAD

**Issue by TheDyreBanana** [Shadows-of-Fire/ClickMachine#37]
Shift clicking any item into the click machine will hard crash the client to desktop. This happens with no other mods installed.

**Comment by Shadows-of-Fire** [comment]
version?

**Comment by TheDyreBanana** [comment]
1.18.1 6.0.0

**Comment by Shadows-of-Fire** [comment]
fixed in Placebo 6.0.2
