### ISSUE TITLE
Crash involving Overloaded and ClickMachine

### ISSUE THREAD

**Issue by braingkk** [Shadows-of-Fire/ClickMachine#40]
Crossposting, as the OP didnt bother.

Forge Version: 36.2.22
MC/Mod Version: 1.16.5-4.5.0
https://gist.github.com/braingkk/252cf4cade9b2bd58f5116e405dd9967

https://github.com/CJ-MC-Mods/Overloaded/issues/112

**Comment by Shadows-of-Fire** [comment]
https://github.com/Shadows-of-Fire/ClickMachine/blob/8a91602ef33b54d8d1dbd19fa90202d2cfabf04b/src/main/java/shadows/click/util/FakePlayerUtil.java#L223
This is the line in question - it's a vanilla call where you don't even pass in any entity parameters. I think there might be other shenanigans at play.
