### ISSUE TITLE
Random crashes since usage of ClickMachine Mod

### ISSUE THREAD

**Issue by JustBuddy** [Shadows-of-Fire/ClickMachine#41]
Our Server is experiencing random crashes since the mod is running on our server.
We would love to continue using this mod, and kindly ask to take a look at this.

MC 1.18.1@Forge 39.0.66
Last crash log: https://mcpaste.io/c7ba5de2959e8dd2

We will unload this mod for the time being.

**Comment by Shadows-of-Fire** [comment]
There is nothing related to CM in that crash report.
That crash you have there looks to be both `solarenergy` and `tesseracts` causing your server to lag too much.
