### ISSUE TITLE
integer overflow on display

### ISSUE THREAD

**Issue by eslym** [Shadows-of-Fire/ClickMachine#43]
![image](https://user-images.githubusercontent.com/3667594/164250016-7918e250-a37f-42e5-abad-16f25df06c1e.png)
minecraft 1.8.2, forge version 40.1.0, mod version 6.0.5

the value is always interpreted correctly, but sometimes it will displayed as overflowed value when open the gui

**Comment by Shadows-of-Fire** [comment]
Fixed in Placebo 6.4.2
