### ISSUE TITLE
keep crashing when leave a item inside the click machine

### ISSUE THREAD

**Issue by bstlyc** [Shadows-of-Fire/ClickMachine#45]
so the mod works but it keeps crashing when i re-open minecraft with the machine filled with item

**Comment by Shadows-of-Fire** [comment]
You'll need to provide a crash report.

**Comment by bstlyc** [comment]
[crash-2022-06-26_04.41.15-server.txt](https://github.com/Shadows-of-Fire/ClickMachine/files/8985611/crash-2022-06-26_04.41.15-server.txt)

**Comment by Shadows-of-Fire** [comment]
This looks like a bug in the toolswap mod, which is either receiving events on the wrong side or not checking for fake players.

**Comment by bstlyc** [comment]
oh ok thanks for the info ill try to delete the tool swap mod first and give update about it
