### ISSUE TITLE
Free Textures For Shadows

### ISSUE THREAD

**Issue by TeetoKaziim** [Shadows-of-Fire/ClickMachine#8]
Here's some textures in case you want them. Maybe you don't want them. That's okay too.

And yes: I dead-ass don't know how to use github.com

![default](https://user-images.githubusercontent.com/25490944/44686320-76db8a80-aa13-11e8-8467-cab66d311e9d.png)
![front](https://user-images.githubusercontent.com/25490944/44686457-ecdff180-aa13-11e8-9d75-596bfeab4464.png)

Image of it in action in an actual minecraft world. Such diorite. Much chorus flower.
![image](https://user-images.githubusercontent.com/25490944/44686379-a25e7500-aa13-11e8-94f8-8fd09cc3ffcb.png)

Happy birthday.

**Comment by Shadows-of-Fire** [comment]
Note to self: remember this exists

**Comment by TheDeviantCrafter** [comment]
Note to Shadow: This exists
